name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-linux-amd64:
    uses: ./.github/workflows/_so_build.yml
    with:
      platform: "@llvm//platforms:linux_amd64"
      artifact-name: "flashattn-linux-amd64.tar.zst"

  build-linux-arm64:
    uses: ./.github/workflows/_so_build.yml
    with:
      platform: "@llvm//platforms:linux_arm64"
      artifact-name: "flashattn-linux-arm64.tar.zst"
