name: Release

on:
  push:
    tags:
      - "*"
      - "!nightly-*"

concurrency:
  group: ${{ github.workflow_sha }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  flash-attention-artifacts:
    uses: ./.github/workflows/_build.yaml

  release:
    name: Release flash-attention artifacts
    needs: ["flash-attention-artifacts"]
    runs-on: ubuntu-latest
    steps:
      - run: rm -rf flash-attention_*.tar.gz

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Publish release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz/*.tar.gz
